name: osc_flutter
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_webview_plugin: ^0.3.3
  shared_preferences: ^0.5.2
  event_bus: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  #导航栏图标
  - assets/images/ic_nav_news_normal.png
  - assets/images/ic_nav_news_actived.png
  - assets/images/ic_nav_tweet_normal.png
  - assets/images/ic_nav_tweet_actived.png
  - assets/images/ic_nav_discover_normal.png
  - assets/images/ic_nav_discover_actived.png
  - assets/images/ic_nav_my_normal.png
  - assets/images/ic_nav_my_pressed.png
  #抽屉布局头部
  - assets/images/cover_img.jpg
  - assets/images/ic_avatar_default.png

